url: "https://Spitfire-Cluster-Community.github.io"
baseurl: "/ase-pe-pvp"
title: SpitfireCluster - ASE PE 1000x PvP - Handbook
name: SC ASE PE 1000x PvP
description: Provides a comprehensive guide on how to embark a journey within the SpitfireCluster Ark Primal Eternal 1000x PvP environment.
repository: Spitfire-Cluster-Community/ase-pe-pvp
google-analytics: G-3VX767JBK1
plugins:
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
collections:
  articles:
    permalink: /:title/
    output: true
  terms:
    permalink: /glossary/:title/
    output: true
defaults:
  -
    scope:
      path: ""
      type: articles
    values:
      layout: page
  -
    scope:
      path: ""
      type: terms
    values:
      layout: term
